### PR TITLE
Rename `coverage` to `distribution`

### PR DESCRIPTION
**Pull request by Janiczek**
Based on a last-minute discussion in the Incremental Elm Discord #elm-test channel and a poll in the Elm Slack #testing channel.

### CODE REVIEW

**Comment by mpizenberg** [comment]
I'm curious, why have the now `Distribution` module (ex `Coverage`) be inside `Test` instead of inside `Fuzz`? is this because of some import cycle issues?

**Comment by Janiczek** [comment]
@mpizenberg I'd say it could live in either! I guess I put it into Test directory to be closer to the `Test.fuzzWith` (that's where the values will be used), but I could imagine
```elm
Test.fuzzWith
  { runs = 1000
  , distribution =
    Test.expectDistribution
      [ Fuzz.Distribution.atLeast 5 "balanced" Tree.isBalanced
     -- ^^^^
      ]
  }
  treeFuzzer
  "Assert something about trees"
  (\tree -> Expect.foo)
```

WDYT, does it read better, should it belong there?

**Comment by lue-bird** [comment]
`Test.FuzzDistribution`?

**Comment by mpizenberg** [comment]
I asked this mostly for the purpose of API documentation. I'd expect this
feature documentation to be located close to Fuzz documentation. If it
better fits the documentation flow in the Test namespace, let's leave it
there, and maybe add a "Fuzz" prefix as Lue suggests. If it better fits
within the Fuzz module doc, maybe we move it there?

PS I haven't read the API docs of the new API so I may be totally wrong.

**Comment by Janiczek** [comment]
@mpizenberg Here are the API docs (only those relevant to distribution):

## Table of Contents

Screenshot 2022-10-11 at 13 12 25

## Test

Screenshot 2022-10-11 at 13 11 14
Screenshot 2022-10-11 at 13 11 25
Screenshot 2022-10-11 at 13 11 32
Screenshot 2022-10-11 at 13 11 40

## Test.Distribution

Screenshot 2022-10-11 at 13 12 01
Screenshot 2022-10-11 at 13 12 07
Screenshot 2022-10-11 at 13 12 10

## Test.Runner

Screenshot 2022-10-11 at 13 12 16

**Pull request merged**
