### PR TITLE
merge release/1.2.2 to master

### PR DESCRIPTION
**Pull request by avh4**
Version 1.2.2 was released.  This PR is to merge those changes back into master.  It includes the following:

- Fix CI to work with latest versions of node
- #96 Fix handling of nested Html.lazy
- Other changes from 1.2.1 that weren't yet merged to master

TODO:

- [x] did I lose any changes to src/Shrink.elm from the 1.2.x branch when resolving conflicts?  (The file was renamed on master?)
- [x] remove https://github.com/elm-explorations/test/pull/99/commits/2cf4d7874373d4d4bbc7b15d88c9f48323c9878c

### CODE REVIEW

**Comment by avh4** [comment]
Checking "did I lose any changes to src/Shrink.elm from the 1.2.x branch when resolving conflicts? (The file was renamed on master?)"

Common ancestor is e9705dd2fdeeb2aabad630b09ec9812760851d3a

```diff
git diff e9705dd2fdeeb2aabad630b09ec9812760851d3a..1.2.2 -- src/Shrink.elm
diff --git a/src/Shrink.elm b/src/Shrink.elm
index 4600313..b500b92 100644
--- a/src/Shrink.elm
+++ b/src/Shrink.elm
@@ -527,9 +527,9 @@ conjunction with `andMap`. For example:
     vector : Shrinker Vector
     vector { x, y, z } =
         Vector
-            `map` float x
-            `andMap` float y
-            `andMap` float z
+            |> map (float x)
+            |> andMap (float y)
+            |> andMap (float z)
 
 -}
 map : (a -> b) -> LazyList a -> LazyList b
```

**Comment by mgold** [comment]
I thought we wanted to remove `Expect.true` and `Expect.false` in the next major release. This brings them back.

**Comment by avh4** [comment]
It looks like that's because of this commit included in 1.2.1?  https://github.com/elm-explorations/test/pull/99/commits/2cf4d7874373d4d4bbc7b15d88c9f48323c9878c  I guess that needs to be removed, then.

**Comment by rtfeldman** [comment]
Looks good! Thanks to all who contributed to this release. 💚

**Pull request merged**
