### PR TITLE
Fix CI and update to elm 0.19.1

### PR DESCRIPTION
**Pull request by harrysarson**
- fix CI in new node versions by bumping deps
- simplify ci config
- ~~upgrade to elm 0.19.1~~

### CODE REVIEW

**Comment by harrysarson** [comment]
We could just pick the first commit (the second two are more controversial)

**Comment by harrysarson** [comment]
I do not understand:

```
elm-format --validate src tests/src benchmarks

{

  "name": "elm-test-tests",

  "version": "0.0.0",

  "description": "tests for elm-test, so you can elm-test while you elm-test",

  "scripts": {

    "test": "cat package.json && elm --version && elm make --docs=documentation.json && (cd tests && ./test.sh) && elm-format --validate src tests/src benchmarks"

  },

  "author": "Richard Feldman",

  "license": "BSD-3-Clause",

  "devDependencies": {

    "elm": "latest-0.19.0",

    "elm-format": "latest-0.19.0"

  },

  "dependencies": {}

}

0.19.1

...
```

**Comment by harrysarson** [comment]
Okay, I tracked the issue with failing CI down. The problem is that node_modules are cached and therefore the wrong version of elm is used. The solution is to delete the cache, although someone with commit access to this repository will need to do so (see image).

image

---

Tagging @rtfeldman and @mgold as folk I think have commit access here.

**Comment by drathier** [comment]
I have commit access. Nuked the caches and rebuilt, it's green now :)

**Comment by harrysarson** [comment]
Thanks! Prior to this change we only ran of x86 Linux and x86 macos. Those platforms will have identical floating point behaviour (or so I believe as they both have 64 bit intel processors)

**Comment by drathier** [comment]
Iirc we had exact matching float tests for expectWithin at first, but it failed in CI. Then I ran the tests locally on Windows and Mac and they differed. Afaik architecture, cpu generation and OS can all affect float calculations, so I think we should test broadly.

**Comment by harrysarson** [comment]
@drathier you have convinced me that most my changes to .travis.yml were misguided. I have rebased and now only the redundant parts of the ci config have been changed.

This is good to go from my point of view.

**Comment by drathier** [comment]
All good then :) Thanks for helping out!

**Pull request merged**
